name = "VehicleRoutingSynPre"
uuid = "c4bc0f33-d28c-4039-a744-848cfd7daba4"
authors = ["Payakorn Saksuriya"]
version = "0.1.0"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[compat]
JLD2 = "0.4"
Latexify = "0.15"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
